
# Site settings
title: RaiHogar - Limpieza and Servicios de Hogar en Torremolinos
email: rai@raihogar.com
description: "Limpieza and Servicios de Hogar: Ofrecemos un servicio impecable de Limpieza y Servicios de Hogar como cuidado de ropa, lavado y planchado"


# Team names, titles and social links
people:
- name: Raimunda Rodrigues Goncalves
  pic: raimunda2
  position: Professional de Servicio de Hogar
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/HogarRai


# Postal address (add as many lines as necessary)
address:
  - line: Torremolinos

# Build settings
markdown: kramdown
permalink: pretty

